- name: Create mongo certs group
  group:
    name: "{{ mongo_certs_group }}"
    state: present

- name: Ensure mongo user exists
  user:
    name: "{{ mongo_user }}"
    groups: "{{ mongo_certs_group }}"
    state: present

- name: Ensure vault agent user exists
  user:
    name: "{{ vault_agent_user }}"
    groups: "{{ mongo_certs_group }}"
    state: present
