- name: Ensure mongo group exists
  group:
    name: "{{ mongo_group }}"
    state: present

- name: Ensure mongo user exists
  user:
    name: "{{ mongo_user }}"
    groups: "{{ mongo_group }}"
    state: present

- name: Ensure mongo vault agent group exists
  group:
    name: "{{ mongo_vault_agent_group }}"
    state: present

- name: Ensure mongo vault agent user exists
  user:
    name: "{{ mongo_vault_agent_user }}"
    groups:
      - "{{ vault_agent_navigational_group }}"
      - "{{ vault_agent_authorities_group }}"
      - "{{ mongo_vault_agent_group }}"
      - "{{ vault_agent_bin_group }}"
    state: present
