- name: Include create users tasks
  import_tasks: createUsers.yaml

- name: Include mkdirs tasks
  import_tasks: mkdirs.yaml

- name: Check if vaultServerClient.crt exists
  ansible.builtin.stat:
    path: "{{ vault_dir }}/certs/mongo/vaultServerClient.crt"
  register: vault_key_stat

- name: Include certs tasks
  import_tasks: certs.yaml
  when: not vault_key_stat.stat.exists

- name: Include binaries tasks
  import_tasks: binaries.yaml

- name: Include apparmor tasks
  import_tasks: apparmor.yaml

- name: Check if mongo-vault-agent service is running
  shell: systemctl is-active mongo-vault-agent
  register: mongo_vault_agent_status
  ignore_errors: true

- name: Include vault tasks
  import_tasks: vault.yaml
  when: mongo_vault_agent_status.stdout != "active"
