- name: Include create users tasks
  import_tasks: createUsers.yaml

- name: Include mkdirs tasks
  import_tasks: mkdirs.yaml

- name: Include binaries tasks
  import_tasks: binaries.yaml

- name: Check if mongo-vault-agent service is running
  shell: systemctl is-active mongo-vault-agent
  register: mongo_vault_agent_status
  ignore_errors: true

- name: Include vault tasks
  import_tasks: vault.yaml
  when: mongo_vault_agent_status.stdout != "active"
