- name: Create empty vault.pid file
  file:
    path: "{{ mongo_base_dir }}/vault/vault.pid"
    state: touch
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0644"
  become: true

- name: Copy Vault Agent config
  template:
    src: /home/fg/Desktop/vault/mongo-1/agent-config.hcl.j2
    dest: "{{ mongo_base_dir }}/vault/agent-config.hcl"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0600"

- name: Copy Vault Agent mongodb.pem template
  copy:
    src: /home/fg/Desktop/vault/mongo-1/mongodb.pem.ctmpl
    dest: "{{ mongo_base_dir }}/vault/templates/mongodb.pem.ctmpl"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0600"

- name: Copy Vault Agent mongodb-keyfile template
  copy:
    src: /home/fg/Desktop/vault/mongo-1/mongodb-keyfile.ctmpl
    dest: "{{ mongo_base_dir }}/vault/templates/mongodb-keyfile.ctmpl"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0600"

- name: Deploy vault credential fetcher
  copy:
    dest: "{{ mongo_base_dir }}/vault/scripts/restart-mongo-services.sh"
    owner: root
    group: "{{ vault_agent_group }}"
    mode: "0750"
    content: |
      {{ lookup('file', 'scripts/restart-mongo-services.sh') | indent(6) }}

- name: Add sudoers rule for {{ vault_agent_user }} to run restart script and chown certs
  copy:
    dest: /etc/sudoers.d/{{ vault_agent_user }}-mongo
    content: |
      {{ vault_agent_user }} ALL=(ALL) NOPASSWD: \
        {{ mongo_base_dir }}/vault/scripts/restart-mongo-services.sh, \
        /bin/systemctl restart mongod-configsvr.service, \
        /bin/systemctl restart mongos.service, \
        /bin/systemctl restart mongod-shardsvr.service, \
        /bin/chown
    owner: root
    group: root
    mode: "0440"

- name: Create systemd service file for vault agent
  copy:
    dest: /etc/systemd/system/vault-agent.service
    content: |
      [Unit]
      Description=Vault Agent
      After=network.target fetch-vault-mongo-approle-ids.service
      Requires=fetch-vault-mongo-approle-ids.service

      [Service]
      User={{ vault_agent_user }}
      Group={{ vault_agent_group}}
      ExecStart={{ mongo_base_dir }}/bin/vault agent -config={{ mongo_base_dir }}/vault/agent-config.hcl
      Restart=on-failure
      PIDFile={{ mongo_base_dir }}/vault/vault.pid

      [Install]
      WantedBy=multi-user.target

- name: Start and enable Vault Agent service
  systemd:
    name: vault-agent
    state: stopped
    enabled: yes

- name: Deploy vault credential fetcher
  copy:
    dest: "{{ mongo_base_dir }}/vault/scripts/fetch-vault-mongo-approle-ids.sh"
    owner: root
    group: "{{ vault_agent_group }}"
    mode: "0750"
    content: |
      {{ lookup('file', 'scripts/fetch-vault-mongo-approle-ids.sh') | indent(6) }}

- name: Create systemd unit to run the fetcher on boot
  copy:
    dest: /etc/systemd/system/fetch-vault-mongo-approle-ids.service
    content: |
      [Unit]
      Description=Vault Mongo approle ids fetcher
      After=network-online.target
      Wants=network-online.target

      [Service]
      User={{ vault_agent_user }}
      Group={{ vault_agent_group}}
      Type=oneshot
      ExecStart={{ mongo_base_dir }}/vault/scripts/fetch-vault-mongo-approle-ids.sh
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd

- name: Enable fetch-vault-mongo-approle-ids
  systemd:
    name: fetch-vault-mongo-approle-ids.service
    enabled: yes
