- name: Create empty vault.pid file
  file:
    path: "{{ mongo_base_dir }}/vault/vault.pid"
    state: touch
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0644"
  become: true

- name: Copy Vault role_id
  copy:
    src: "/home/fg/Desktop/vault/mongo-1/role_id"
    dest: "{{ mongo_base_dir }}/certs/secrets/role_id"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0600"

- name: Copy Vault secret_id
  copy:
    src: "/home/fg/Desktop/vault/mongo-1/secret_id"
    dest: "{{ mongo_base_dir }}/certs/secrets/secret_id"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0600"

- name: Copy Vault Agent config
  template:
    src: /home/fg/Desktop/vault/mongo-1/agent-config.hcl.j2
    dest: "{{ mongo_base_dir }}/vault/agent-config.hcl"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0600"

- name: Copy Vault Agent mongodb.pem template
  copy:
    src: /home/fg/Desktop/vault/mongo-1/mongodb.pem.ctmpl
    dest: "{{ mongo_base_dir }}/vault/templates/mongodb.pem.ctmpl"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0600"

- name: Copy Vault Agent mongodb-keyfile template
  copy:
    src: /home/fg/Desktop/vault/mongo-1/mongodb-keyfile.ctmpl
    dest: "{{ mongo_base_dir }}/vault/templates/mongodb-keyfile.ctmpl"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: "0600"

- name: Deploy restart script for MongoDB services
  copy:
    dest: "{{ mongo_base_dir }}/vault/scripts/restart-mongo-services.sh"
    content: |
      #!/bin/bash

      # Fix ownership of rendered certs
      for file in mongodb.pem mongodb-keyfile; do
          sudo chown mongodb:{{ mongo_certs_group }} "{{ mongo_base_dir }}/certs/secrets/$file"
      done

      # Restart MongoDB services
      for svc in mongod-configsvr mongos mongod-shardsvr; do
          systemctl list-units --full -all "$svc.service" | grep -Fq loaded && systemctl restart "$svc"
      done
    owner: root
    group: "{{ vault_agent_group }}"
    mode: "0754"

- name: Add sudoers rule for {{ vault_agent_user }} to run restart script and chown certs
  copy:
    dest: /etc/sudoers.d/{{ vault_agent_user }}-mongo
    content: |
      {{ vault_agent_user }} ALL=(ALL) NOPASSWD: \
        {{ mongo_base_dir }}/vault/scripts/restart-mongo-services.sh, \
        /bin/systemctl restart mongod-configsvr.service, \
        /bin/systemctl restart mongos.service, \
        /bin/systemctl restart mongod-shardsvr.service, \
        /bin/chown
    owner: root
    group: root
    mode: "0440"

- name: Create systemd service file for vault agent
  copy:
    dest: /etc/systemd/system/vault-agent.service
    content: |
      [Unit]
      Description=Vault Agent
      After=network.target

      [Service]
      User={{ vault_agent_user }}
      Group={{ vault_agent_group}}
      ExecStart={{ mongo_base_dir }}/bin/vault agent -config={{ mongo_base_dir }}/vault/agent-config.hcl
      Restart=on-failure
      PIDFile={{ mongo_base_dir }}/vault/vault.pid

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd

- name: Start and enable Vault Agent service
  systemd:
    name: vault-agent
    state: started
    enabled: yes
