- name: Create empty vault-agent.pid file
  file:
    path: "{{ vault_dir }}/agents/mongo/vault-agent.pid"
    state: touch
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0640"
  become: true

- name: Create vault policies
  block:
    - name: "Render Vault policy for mongo-approle-reader"
      template:
        src: "{{ playbook_dir }}/../vault/policies/mongo-approle-reader.hcl.j2"
        dest: "/tmp/mongo-approle-reader-{{ hostvars[inventory_hostname]['ansible_host'] }}.hcl"

    - name: "Read rendered mongo-approle-reader policy file"
      slurp:
        src: "/tmp/mongo-approle-reader-{{ hostvars[inventory_hostname]['ansible_host'] }}.hcl"
      register: slurped_mongo_approle_reader_policy

    - name: "Upload mongo-approle-reader policy to vault"
      delegate_to: localhost
      community.hashi_vault.vault_write:
        url: "{{ vault_url }}"
        token: "{{ vault_token }}"
        path: "sys/policies/acl/mongo-approle-reader-{{ hostvars[inventory_hostname]['ansible_host'] }}"
        ca_cert: "{{ local_ca_path }}"
        data:
          policy: "{{ slurped_mongo_approle_reader_policy.content | b64decode }}"

    - name: "Render Vault policy for mongo"
      template:
        src: "{{ playbook_dir }}/../vault/policies/mongo.hcl.j2"
        dest: "/tmp/mongo-{{ hostvars[inventory_hostname]['ansible_host'] }}.hcl"

    - name: "Read rendered mongo policy file"
      slurp:
        src: "/tmp/mongo-{{ hostvars[inventory_hostname]['ansible_host'] }}.hcl"
      register: slurped_mongo_policy

    - name: "Upload mongo policy to vault"
      delegate_to: localhost
      community.hashi_vault.vault_write:
        url: "{{ vault_url }}"
        token: "{{ vault_token }}"
        path: "sys/policies/acl/mongo-{{ hostvars[inventory_hostname]['ansible_host'] }}"
        ca_cert: "{{ local_ca_path }}"
        data:
          policy: "{{ slurped_mongo_policy.content | b64decode }}"

  always:
    - name: "Clean up temporary policy file"
      file:
        path: "/tmp/mongo-approle-reader-{{ hostvars[inventory_hostname]['ansible_host'] }}.hcl"
        state: absent

    - name: "Clean up temporary policy file"
      file:
        path: "/tmp/mongo-{{ hostvars[inventory_hostname]['ansible_host'] }}.hcl"
        state: absent

- name: "Create AppRole for node"
  community.hashi_vault.vault_write:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    path: "auth/approle/role/mongo-{{ hostvars[inventory_hostname]['ansible_host'] }}"
    ca_cert: "{{ local_ca_path }}"
    data:
      token_policies: "mongo-{{ hostvars[inventory_hostname]['ansible_host'] }}"
      token_ttl: "1h"
      token_max_ttl: "4h"

- name: Copy Vault Agent config
  template:
    src: "{{ playbook_dir }}/../vault/agents/mongo-agent-config.hcl.j2"
    dest: "{{ vault_dir }}/agents/mongo/mongo-agent-config.hcl"
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0400"

- name: Deploy rendered Vault Agent mongodb.pem.ctmpl template
  template:
    src: "{{ playbook_dir }}/../vault/templates/mongodb.pem.ctmpl.j2"
    dest: "{{ vault_dir }}/templates/mongo/mongodb-{{ hostvars[inventory_hostname]['ansible_host'] }}.pem.ctmpl"
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0400"

- name: Copy Vault Agent mongodb-keyfile template
  copy:
    src: "{{ playbook_dir }}/../vault/templates/mongodb-keyfile.ctmpl"
    dest: "{{ vault_dir }}/templates/mongo/mongodb-keyfile.ctmpl"
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0400"

- name: Install mongoApproleVR.conf
  template:
    src: mongoApproleVR.conf.j2
    dest: "{{ mongo_base_dir }}/conf/mongoApproleVR.conf"
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0440"

- name: Add sudoers rule for {{ mongo_vault_agent_user }} to run restart script
  copy:
    dest: /etc/sudoers.d/{{ mongo_vault_agent_user }}-mongo
    content: |
      {{ vault_agent_user }} ALL=(ALL) NOPASSWD: \
        {{ vault_dir }}/scripts/mongo/mongo-vault-restart.sh, \
        /bin/systemctl restart mongod-configsvr.service, \
        /bin/systemctl restart mongos.service, \
        /bin/systemctl restart mongod-shardsvr.service
    owner: root
    group: root
    mode: "0440"

- name: Install fetch-vault-mongo-approle-ids script
  template:
    src: fetch-vault-mongo-approle-ids.sh.j2
    dest: "{{ vault_dir }}/scripts/mongo/fetch-vault-mongo-approle-ids.sh"
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0550"

- name: Create systemd unit to run the fetcher on boot
  copy:
    dest: /etc/systemd/system/fetch-vault-mongo-approle-ids.service
    content: |
      [Unit]
      Description=Vault Mongo approle ids fetcher
      After=network-online.target
      Wants=network-online.target

      [Service]
      User=root
      Group={{ vault_agent_bin_group }}
      Type=oneshot
      ExecStart={{ vault_dir }}/scripts/mongo/fetch-vault-mongo-approle-ids.sh
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Install restart-mongo-services script
  template:
    src: mongo-vault-restart.sh.j2
    dest: "{{ vault_dir }}/scripts/mongo/mongo-vault-restart.sh"
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0550"

- name: Create systemd service file for mongo vault agent
  copy:
    dest: /etc/systemd/system/mongo-vault-agent.service
    content: |
      [Unit]
      Description=Vault Agent
      After=network.target fetch-vault-mongo-approle-ids.service
      Requires=fetch-vault-mongo-approle-ids.service

      [Service]
      User={{ mongo_vault_agent_user }}
      Group={{ mongo_vault_agent_group }}
      ExecStart={{ vault_dir }}/bin/vault agent -config={{ vault_dir }}/agents/mongo/mongo-agent-config.hcl
      Restart=on-failure
      PIDFile={{ vault_dir }}/agents/mongo/mongo-vault-agent.pid

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Force Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable & start fetcher
  systemd:
    name: fetch-vault-mongo-approle-ids.service
    state: started
    enabled: yes
  register: fetcher_status

- name: Start and enable Mongo Vault Agent service
  systemd:
    name: mongo-vault-agent
    state: started
    enabled: yes
