all:
  hosts:
    tableTopNode1:
      ansible_host: 10.40.0.101
    tableTopNode2:
      ansible_host: 10.40.0.102
    tableTopNode3:
      ansible_host: 10.40.0.103

  children:
    config_servers:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    new_config_servers:
      hosts:
        # tableTopNode1:
        # tableTopNode2:
        # tableTopNode3:

    remove_config_servers:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    shard_servers:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    new_shard_servers:
      hosts:
        # tableTopNode1:
        # tableTopNode2:
        # tableTopNode3:

    remove_shard_servers:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    mongos_routers:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:

    remove_mongos_routers:
      hosts:
        tableTopNode1:
        tableTopNode2:
        tableTopNode3:
