- name: Wait for all shard-server members to be reachable
  wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: "{{ shard_port }}"
    timeout: 120
    delay: 5
    state: started
  loop: "{{ groups['shard_servers'] }}"

- name: Include vault_fetcher role
  include_role:
    name: vault-fetcher
  vars:
    fetcher_secret_var_name: "mongo_admin"
    fetcher_secret_path: "{{ mongo_admin_secret_path }}"
    fetcher_vault_token: "{{ vault_token }}"
    fetcher_vault_url: "{{ vault_url }}"
    fetcher_ca_path: "{{ ca_path }}"
    fetcher_engine_version: 2

- name: Add shard to cluster
  become: true
  command: >
    {{ mongo_base_dir }}/bin/mongosh
    "mongodb://admin:{{ mongo_admin.password }}@{{ mongos_node }}:{{ mongos_port }}/admin?tls=true&tlsCAFile={{ vault_dir }}/authorities/ca.pem&tlsCertificateKeyFile={{ vault_dir }}/secrets/mongo/mongodb.pem&directConnection=true"
    --eval '
      const replSet = "{{ repl_set_name }}";
      const hosts = [
        {% for host in groups["shard_servers"] %}
        "{{ hostvars[host].ansible_host }}:{{ shard_port }}"{% if not loop.last %},{% endif %}
        {% endfor %}
      ];
      const shardString = replSet + "/" + hosts.join(",");
      sh.addShard(shardString);
    '
