- name: Stop mongos service
  ansible.builtin.systemd:
    name: mongos.service
    state: stopped
    enabled: no
  become: true

- name: Kill mongos process (ignoring failure if not running)
  command: |
    pkill -F "{{ mongo_base_dir }}/mongos/logs/mongos.pid"
  ignore_errors: true
  become: true

- name: Remove mongos systemd service file
  ansible.builtin.file:
    path: /etc/systemd/system/mongos.service
    state: absent
  become: true

- name: Remove all contents of {{ mongo_base_dir }}/mongos
  command: rm -rf "{{ mongo_base_dir }}/mongos"
  ignore_errors: true
  become: true

- name: Check if shard directory exists
  stat:
    path: "{{ mongo_base_dir }}/shard"
  register: shard_dir

- name: Check if config directory exists
  stat:
    path: "{{ mongo_base_dir }}/config"
  register: config_dir

# - name: Unmount tmpfs if mounted
#   mount:
#     path: "{{ mongo_base_dir }}/certs/secrets"
#     state: unmounted
#   when: not shard_dir.stat.exists and not config_dir.stat.exists
#   ignore_errors: true

# - name: Remove tmpfs mount from fstab
#   lineinfile:
#     path: /etc/fstab
#     regexp: '^tmpfs\s+{{ mongo_base_dir }}/certs/secrets\s+tmpfs'
#     state: absent
#   when: not shard_dir.stat.exists and not config_dir.stat.exists
#   notify: Reload systemd daemon (if needed)

- name: Remove {{ mongo_base_dir }}/certs if shard and config directories are missing
  file:
    path: "{{ mongo_base_dir }}/certs"
    state: absent
  when: not shard_dir.stat.exists and not config_dir.stat.exists
  become: true

- name: Remove {{ mongo_base_dir }}/bin if shard and config directories are missing
  file:
    path: "{{ mongo_base_dir }}/bin"
    state: absent
  when: not shard_dir.stat.exists and not config_dir.stat.exists
  become: true

- name: Remove {{ mongo_base_dir }}/vault if shard and mongos directories are missing
  file:
    path: "{{ mongo_base_dir }}/vault"
    state: absent
  when: not shard_dir.stat.exists and not config_dir.stat.exists
  become: true
