- name: Kill mongod process (ignoring failure if not running)
  command: |
    pkill -F "{{ mongo_base_dir }}/config/logs/mongod.pid"
  ignore_errors: true
  become: true

- name: Fix ownership of all MongoDB files
  become: true
  file:
    path: "{{ mongo_base_dir }}/config"
    recurse: yes
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"

- name: Disable transparent hugepage defragmentation
  become: true
  shell: |
    echo 'defer+madvise' > /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable transparent hugepage paging
  become: true
  shell: |
    echo '0' > /sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none

- name: Tune vm.swappiness to 1 (avoid swapping)
  become: true
  sysctl:
    name: vm.swappiness
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Render mongod “auth” config file
  template:
    src: mongod.conf.j2
    dest: "{{ mongo_base_dir }}/config/conf/mongod.conf"
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
    mode: "0644"

- name: Create systemd service file for MongoDB config server
  copy:
    dest: /etc/systemd/system/mongod-configsvr.service
    content: |
      [Unit]
      Description=MongoDB Config Server
      After=network.target

      [Service]
      Type=simple
      User=mongodb
      Group=mongodb
      WorkingDirectory={{ mongo_base_dir }}
      LimitNOFILE=64000
      Environment=GLIBC_TUNABLES=glibc.pthread.rseq=0
      ExecStart={{ mongo_base_dir }}/bin/mongod \
        --config "{{ mongo_base_dir }}/config/conf/mongod.conf"
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd

- name: Enable and start MongoDB config server service
  systemd:
    name: mongod-configsvr.service
    enabled: yes
    state: started

- name: Remove the temporary no-auth config
  file:
    path: "{{ mongo_base_dir }}/config/conf/mongod-no-auth.conf"
    state: absent

- name: Fix ownership of all MongoDB files
  become: true
  file:
    path: "{{ mongo_base_dir }}/config"
    recurse: yes
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
  notify:
    - Reload systemd
