- name: Include vault_fetcher role
  include_role:
    name: vault-fetcher
  vars:
    fetcher_secret_var_name: "mongo_admin"
    fetcher_secret_path: "{{ mongo_admin_secret_path }}"
    fetcher_vault_token: "{{ vault_token }}"
    fetcher_vault_url: "{{ vault_url }}"
    fetcher_ca_path: "{{ local_ca_path }}"
    fetcher_engine_version: 2

- name: Create x.509 users in $external for mongos servers
  shell: >
    {{ mongo_base_dir }}/bin/mongosh "mongodb://admin:{{ mongo_admin.password | urlencode | replace('/', '%2F') }}@{{ primary_node }}:{{ config_port }}/?replicaSet={{ config_repl_set_name }}&tls=true&tlsCAFile={{ vault_dir }}/authorities/ca.pem&tlsCertificateKeyFile={{ vault_dir }}/secrets/mongo/mongodb-{{ hostvars[inventory_hostname]['ansible_host'] }}.pem&directConnection=true"
    --eval '
      db.getSiblingDB("$external").createUser({
        user: "CN={{ hostvars[item]["ansible_host"] }},OU=MongoClient,O={{ cert_organization }},L={{ cert_locality }},ST={{ cert_state }},C={{ cert_country }}",
        roles: [{ role: "root", db: "admin" }]
      })
    '
  loop: "{{ groups['mongos_routers'] }}"
  loop_control:
    label: "{{ hostvars[item]['ansible_host'] }}"
  run_once: true
  delegate_to: "{{ primary_node }}"
  become: true
  become_user: "{{ mongo_vault_agent_user }}"
