- name: Check if mongos role exists
  community.hashi_vault.vault_read:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    path: "pki/roles/mongos-{{ hostvars[inventory_hostname].ansible_host }}"
  register: mongos_role
  environment:
    REQUESTS_CA_BUNDLE: "{{ local_ca_path }}"
  delegate_to: localhost
  ignore_errors: true

- name: Define PKI role for mongos certs
  community.hashi_vault.vault_write:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    mount_point: ""
    path: "pki/roles/mongos-{{ hostvars[inventory_hostname].ansible_host }}"
    data:
      name: "mongos-{{ hostvars[inventory_hostname].ansible_host }}"
      allowed_domains:
        - "{{ inventory_hostname }}.mongo"
        - "{{ hostvars[inventory_hostname].ansible_host }}"
      key_type: "rsa"
      key_bits: 4096
      country:
        - "{{ cert_country }}"
      province:
        - "{{ cert_state }}"
      locality:
        - "{{ cert_locality }}"
      organization:
        - "{{ cert_organization }}"
      ou:
        - "MongoClient"
      common_name: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      exclude_cn_from_sans: true
      allow_bare_domains: true
      alt_names:
        - "{{ inventory_hostname }}.mongo"
      ip_sans:
        - "{{ hostvars[inventory_hostname].ansible_host }}"
      allow_ip_sans: true
      allow_localhost: false
      server_flag: true
      client_flag: true
      key_usage:
        - DigitalSignature
        - KeyEncipherment
      ext_key_usage:
        - client_auth
      ttl: "12h"
      max_ttl: "12h"
      renew_before: "1h"
  when: mongos_role.failed
  environment:
    REQUESTS_CA_BUNDLE: "{{ local_ca_path }}"
  delegate_to: localhost
  no_log: true
