- name: Create MongoDB log/conf directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
    mode: "0755"
  loop:
    - "{{ mongo_base_dir }}/mongos/logs"
    - "{{ mongo_base_dir }}/mongos/conf"

- name: Create empty mongos.pid file
  file:
    path: "{{ mongo_base_dir }}/mongos/logs/mongos.pid"
    state: touch
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
    mode: "0644"
  become: true

- name: Render mongod “auth” config file
  template:
    src: mongos.conf.j2
    dest: "{{ mongo_base_dir }}/mongos/conf/mongos.conf"
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
    mode: "0644"

- name: Create mongos systemd unit
  copy:
    dest: /etc/systemd/system/mongos.service
    content: |
      [Unit]
      Description=MongoDB Shard Router
      After=network.target

      [Service]
      User=mongodb
      ExecStart={{ mongo_base_dir }}/bin/mongos --config {{ mongo_base_dir }}/mongos/conf/mongos.conf
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start mongos
  systemd:
    daemon_reload: true
    name: mongos
    enabled: true
    state: started

- name: Fix ownership of all MongoDB files
  become: true
  file:
    path: "{{ mongo_base_dir }}/mongos"
    recurse: yes
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
  notify:
    - Reload systemd

- name: Wait for mongos to be ready
  wait_for:
    port: "{{ mongos_port }}"
    delay: 3
    timeout: 60
