# Vault
- name: Create {{ vault_dir }}/secrets/mongos directory
  file:
    path: "{{ vault_dir }}/secrets/mongos"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create {{ vault_dir }}/scripts/mongos directory
  file:
    path: "{{ vault_dir }}/scripts/mongos"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create {{ vault_dir }}/templates/mongos directory
  file:
    path: "{{ vault_dir }}/templates/mongos"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

- name: Create {{ vault_dir }}/agents/mongos directory
  file:
    path: "{{ vault_dir }}/agents/mongos"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ vault_agent_navigational_group }}"
    mode: "0710"

# Mongos
- name: Create MongoDB log/conf directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0750"
  loop:
    - "{{ mongo_base_dir }}/mongos/logs"
    - "{{ mongo_base_dir }}/mongos/conf"

- name: Create empty mongos.pid file
  file:
    path: "{{ mongo_base_dir }}/mongos/logs/mongos.pid"
    state: touch
    owner: "{{ mongo_vault_agent_user }}"
    group: "{{ mongo_vault_agent_group }}"
    mode: "0640"
  become: true
