- name: Create MongoDB data/log directories
  file:
    path: "{{ item }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0755'
  loop:
    - /mnt/mongo/shard/data
    - /mnt/mongo/shard/logs

