- name: Wait for all shard-server members to be reachable
  wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: "{{ shard_port }}"
    timeout: 120
    delay: 5
    state: started
  loop: "{{ groups['new_shard_servers'] }}"

- name: Add new servers to replica
  shell: |
    {{ mongo_bin }}/mongosh "mongodb://admin:{{ admin_user_password }}@localhost:{{ shard_port }}/admin?replicaSet={{ repl_set_name }}&tls=true&tlsCAFile={{ mongo_cert_dir }}/ca.pem&tlsCertificateKeyFile={{ mongo_cert_dir }}/mongodb.pem&directConnection=true" --eval '
    const currentConfig = rs.conf();
    let maxId = -1;
    for (const m of currentConfig.members) {
      if (m._id > maxId) maxId = m._id;
    }

    {% for host in groups["new_shard_servers"] %}
    maxId++;
    rs.add({ _id: maxId, host: "{{ hostvars[host].ansible_host }}:{{ shard_port }}" });
    sleep(1000);
    {% endfor %}
    '
  run_once: true
