- name: Delete mongo-approle-reader policy from Vault
  delegate_to: localhost
  uri:
    url: "{{ vault_url }}/v1/sys/policies/acl/mongo-approle-reader-{{ hostvars[inventory_hostname]['ansible_host'] }}"
    method: DELETE
    headers:
      "X-Vault-Token": "{{ vault_token }}"
    validate_certs: yes
    status_code: 204
  environment:
    REQUESTS_CA_BUNDLE: "{{ local_ca_path }}"
  register: delete_policy_reader

- name: Delete mongo policy from Vault
  delegate_to: localhost
  uri:
    url: "{{ vault_url }}/v1/sys/policies/acl/mongo-{{ hostvars[inventory_hostname]['ansible_host'] }}"
    method: DELETE
    headers:
      "X-Vault-Token": "{{ vault_token }}"
    validate_certs: yes
    status_code: 204
  environment:
    REQUESTS_CA_BUNDLE: "{{ local_ca_path }}"
  register: delete_policy_mongo

- name: Delete AppRole from Vault
  delegate_to: localhost
  uri:
    url: "{{ vault_url }}/v1/auth/approle/role/mongo-{{ hostvars[inventory_hostname]['ansible_host'] }}"
    method: DELETE
    headers:
      "X-Vault-Token": "{{ vault_token }}"
    validate_certs: yes
    status_code: 204
  environment:
    REQUESTS_CA_BUNDLE: "{{ local_ca_path }}"
  register: delete_approle

- name: Delete each Mongo TLS secret from Vault (KV v2)
  delegate_to: localhost
  uri:
    url: "{{ vault_url }}/v1/secret/metadata/mongo/{{ hostvars[inventory_hostname].ansible_host }}/{{ item.suffix }}"
    method: DELETE
    headers:
      "X-Vault-Token": "{{ vault_token }}"
    validate_certs: yes
    status_code: 204
  environment:
    REQUESTS_CA_BUNDLE: "{{ local_ca_path }}"
  loop:
    - { suffix: "cnf" }
    - { suffix: "csr" }
    - { suffix: "key" }
    - { suffix: "crt" }
    - { suffix: "pem" }
  loop_control:
    label: "{{ item.suffix }}"
