- name: Create MongoDB data/log/conf directories
  file:
    path: "{{ item }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: "0755"
  loop:
    - "{{ mongo_data_dir }}"
    - "{{ mongo_log_dir }}"
    - "{{ mongo_conf_dir }}"

- name: Create empty mongod.pid file
  file:
    path: "{{ mongo_log_dir }}/mongod.pid"
    state: touch
    owner: mongodb
    group: mongodb
    mode: "0644"
  become: true

- name: Render mongod shard “no-auth” config file
  template:
    src: mongod-no-auth.conf.j2
    dest: "{{ mongo_conf_dir }}/mongod-no-auth.conf"
    owner: mongodb
    group: mongodb
    mode: "0644"

- name: Start MongoDB without auth
  shell: >
    {{ mongo_bin }}/mongod
    --config "{{ mongo_conf_dir }}/mongod-no-auth.conf"
  args:
    creates: "{{ mongo_log_dir }}/mongod.log"

- name: Wait for MongoDB port to be open
  wait_for:
    host: localhost
    port: "{{ shard_port }}"
    timeout: 60
    delay: 5
