- name: Wait for all shard-server members to be reachable
  wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: "{{ shard_port }}"
    timeout: 120
    delay: 5
    state: started
  loop: "{{ groups['shard_servers'] }}"

- name: Initiate replica set
  shell: >
    {{ mongo_base_dir }}/bin/mongosh "mongodb://{{ primary_node }}:{{ shard_port }}/?tls=true&tlsCAFile={{ vault_dir }}/authorities/ca.pem&tlsCertificateKeyFile={{ vault_dir }}/secrets/mongo/mongodb.pem&directConnection=true"
    --eval 'rs.initiate({ _id: "{{ repl_set_name }}", members: [ { _id: 0, host: "{{ primary_node }}:{{ shard_port }}", priority: 2 } ] })'
  run_once: true
  register: rs_initiate_result
  failed_when: rs_initiate_result.rc != 0 and '"already initialized"' not in rs_initiate_result.stderr
  become: true

- name: Wait for primary election
  shell: >
    {{ mongo_base_dir }}/bin/mongosh "mongodb://{{ primary_node }}:{{ shard_port }}/?tls=true&tlsCAFile={{ vault_dir }}/authorities/ca.pem&tlsCertificateKeyFile={{ vault_dir }}/secrets/mongo/mongodb.pem&directConnection=true"
    --quiet --eval 'while(rs.status().myState != 1) { sleep(1000); }'
  run_once: true
  become: true

- name: Add other members to the replica set
  shell: >
    {{ mongo_base_dir }}/bin/mongosh "mongodb://{{ primary_node }}:{{ shard_port }}/?replicaSet={{ repl_set_name }}&tls=true&tlsCAFile={{ vault_dir }}/authorities/ca.pem&tlsCertificateKeyFile={{ vault_dir }}/secrets/mongo/mongodb.pem&directConnection=true"
    --eval 'rs.add({ _id: {{ server_id }}, host: "{{ server }}:{{ shard_port }}", priority: 1 })'
  loop: "{{ groups['shard_servers'] | map('extract', hostvars, 'ansible_host') | list }}"
  loop_control:
    index_var: idx
    loop_var: server
  when: server != primary_node
  vars:
    server_id: "{{ idx + 1 }}"
  run_once: true
  become: true

- name: Disable Mongo telemetry
  shell: >
    {{ mongo_base_dir }}/bin/mongosh "mongodb://{{ primary_node }}:{{ shard_port }}/?replicaSet={{ repl_set_name }}&tls=true&tlsCAFile={{ vault_dir }}/authorities/ca.pem&tlsCertificateKeyFile={{ vault_dir }}/secrets/mongo/mongodb.pem&directConnection=true"
    --eval 'disableTelemetry()'
  run_once: true
  become: true

- name: Include vault_fetcher role
  include_role:
    name: vault-fetcher
  vars:
    fetcher_secret_var_name: "mongo_admin"
    fetcher_secret_path: "{{ mongo_admin_secret_path }}"
    fetcher_vault_token: "{{ vault_token }}"
    fetcher_vault_url: "{{ vault_url }}"
    fetcher_ca_path: "{{ local_ca_path }}"
    fetcher_engine_version: 2

- name: Create admin user
  shell: >
    {{ mongo_base_dir }}/bin/mongosh "mongodb://{{ primary_node }}:{{ shard_port }}/?replicaSet={{ repl_set_name }}&tls=true&tlsCAFile={{ vault_dir }}/authorities/ca.pem&tlsCertificateKeyFile={{ vault_dir }}/secrets/mongo/mongodb.pem&directConnection=true"
    --eval 'db.getSiblingDB("admin").createUser({ user: "admin", pwd: "{{ mongo_admin.password }}", roles: [ { role: "root", db: "admin" } ] })'
  run_once: true
  become: true
