- name: Create MongoDB data/log directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
    mode: "0750"
  loop:
    - "{{ mongo_base_dir }}/shard/data"
    - "{{ mongo_base_dir }}/shard/logs"
    - "{{ mongo_base_dir }}/shard/conf"

- name: Disable transparent hugepage defragmentation
  become: true
  shell: |
    echo 'defer+madvise' > /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable transparent hugepage paging
  become: true
  shell: |
    echo '0' > /sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none

- name: Tune vm.swappiness to 1 (avoid swapping)
  become: true
  sysctl:
    name: vm.swappiness
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Render mongod shard “auth” config file
  template:
    src: mongod.conf.j2
    dest: "{{ mongo_base_dir }}/shard/conf/mongod.conf"
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
    mode: "0440"

- name: Create systemd service file for MongoDB shard server
  copy:
    dest: /etc/systemd/system/mongod-shardsvr.service
    content: |
      [Unit]
      Description=MongoDB Shard Server
      After=network.target vault-agent.service
      Requires=vault-agent.service

      [Service]
      Type=simple
      User="{{ mongo_user }}"
      Group="{{ mongo_group }}"
      WorkingDirectory={{ mongo_base_dir }}
      LimitNOFILE=64000
      Environment=GLIBC_TUNABLES=glibc.pthread.rseq=0
      ExecStart={{ mongo_base_dir }}/bin/mongod \
        --config "{{ mongo_base_dir }}/shard/conf/mongod.conf"
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd

- name: Enable and start MongoDB shard server service
  systemd:
    name: mongod-shardsvr.service
    enabled: yes
    state: started

- name: Fix ownership of all MongoDB files
  become: true
  file:
    path: "{{ mongo_base_dir }}/shard"
    recurse: yes
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
  notify:
    - Reload systemd

- name: Wait for MongoDB port to be open
  ignore_errors: true
  wait_for:
    host: localhost
    port: "{{ shard_port }}"
    timeout: 60
    delay: 5

- name: Fix ownership of all MongoDB files
  become: true
  file:
    path: "{{ mongo_base_dir }}/shard"
    recurse: yes
    owner: "{{ mongo_user }}"
    group: "{{ mongo_group }}"
  notify:
    - Reload systemd

- name: Wait for MongoDB port to be open
  ignore_errors: true
  wait_for:
    host: localhost
    port: "{{ shard_port }}"
    timeout: 60
    delay: 5
