- name: Add Mongos routers
  hosts: mongos_routers
  become: true
  vars_files:
    - ../vars/share.yaml
    - ../vars/mongos_routers.yaml
  roles:
    - role: share
    - role: apparmor-mongos
    - role: apparmor-mongosh
    - role: add-mongos-routers
