- name: Set up new Shard Servers - Server Set up
  hosts: new_shard_servers
  become: true
  vars_files:
    - ../vars/shard_servers.yaml
  roles:
    - role: share
    - role: add-new-shard-servers

- name: Set up new Shard Servers - add to replica set
  hosts: tableTopNode1
  become: true
  vars_files:
    - ../vars/shard_servers.yaml
  roles:
    - role: add-new-shard-servers-add-to-replica-set
