- name: Add Mongos routers
  hosts: tableTopNode1
  become: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
  vars_files:
    - ../vars/share.yaml
    - ../vars/mongos_routers.yaml
  roles:
    - role: add-mongos-x509

- name: Add Mongos routers
  hosts: mongos_routers
  become: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
  vars_files:
    - ../vars/share.yaml
    - ../vars/mongos_routers.yaml
  roles:
    - role: share
    - role: apparmor-mongos
    - role: apparmor-mongosh
    - role: add-mongos-routers
