- name: Set up new Shard Servers - Server Set up
  hosts: new_shard_servers
  become: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
  vars_files:
    - ../vars/share.yaml
    - ../vars/shard_servers.yaml
  roles:
    - role: share
    - role: apparmor-mongod
    - role: apparmor-mongosh
    - role: add-new-shard-servers

- name: Set up new Shard Servers - add to replica set
  hosts: tableTopNode1
  become: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
  vars_files:
    - ../vars/share.yaml
    - ../vars/shard_servers.yaml
  roles:
    - role: add-new-shard-servers-add-to-replica-set
