- name: Set up new Config Servers - Server Set up
  hosts: new_config_servers
  become: true
  vars_files:
    - ../vars/config_servers.yaml
  roles:
    - role: share
    - role: add-new-config-servers

- name: Set up new Config Servers - add to replica set
  hosts: tableTopNode1
  become: true
  vars_files:
    - ../vars/config_servers.yaml
  roles:
    - role: add-new-config-servers-add-to-replica-set
