- name: Remove Mongos routers
  hosts: remove_mongos_routers
  become: true
  vars_prompt:
    - name: vault_token
      prompt: "Enter Vault access token"
      private: true
  vars_files:
    - ../vars/share.yaml
    - ../vars/mongos_routers.yaml
  roles:
    - role: remove-mongos-routers
