- name: Set up Config Servers - Server Set up
  hosts: config_servers
  become: true
  vars:
    mongo_cert_dir: /mnt/mongo/certs
    mongo_bin: /mnt/mongo/bin
    mongo_data_dir: /mnt/mongo/config/data
    mongo_log_dir: /mnt/mongo/config/logs
    mongo_conf_dir: /mnt/mongo/config/conf
    repl_set_name: cfgRS1
    mongo_port: 27019
    admin_user_password: tableTopAbigailDavis
  roles:
    - role: share
    - role: config-servers-server-setup
    
- name: Set up Config Servers - Init replica
  hosts: config_servers
  become: true
  run_once: true
  vars:
    mongo_cert_dir: /mnt/mongo/certs
    mongo_bin: /mnt/mongo/bin
    mongo_data_dir: /mnt/mongo/config/data
    mongo_log_dir: /mnt/mongo/config/logs
    mongo_conf_dir: /mnt/mongo/config/conf
    repl_set_name: cfgRS1
    mongo_port: 27019
    admin_user_password: tableTopAbigailDavis
  roles:
    - role: config-servers-replica-init
    
- name: Set up Config Servers - Auth start up
  hosts: config_servers
  become: true
  vars:
    mongo_cert_dir: /mnt/mongo/certs
    mongo_bin: /mnt/mongo/bin
    mongo_data_dir: /mnt/mongo/config/data
    mongo_log_dir: /mnt/mongo/config/logs
    mongo_conf_dir: /mnt/mongo/config/conf
    repl_set_name: cfgRS1
    mongo_port: 27019
    admin_user_password: tableTopAbigailDavis
  roles:
    - role: config-servers-auth-start-up
