- name: Wait for all config-server members to be reachable
  wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: "{{ config_port }}"
    timeout: 120
    delay: 5
    state: started
  loop: "{{ groups['new_config_servers'] }}"

- name: Include vault_fetcher role
  include_role:
    name: vault-fetcher
  vars:
    fetcher_secret_var_name: "mongo_admin"
    fetcher_secret_path: "{{ mongo_admin_secret_path }}"
    fetcher_vault_token: "{{ vault_token }}"
    fetcher_vault_url: "{{ vault_url }}"
    fetcher_ca_path: "{{ ca_path }}"
    fetcher_engine_version: 2

- name: Add new servers to replica
  shell: |
    {{ mongo_base_dir }}/bin/mongosh "mongodb://admin:{{ mongo_admin.password }}@localhost:{{ config_port }}/admin?replicaSet={{ repl_set_name }}&tls=true&tlsCAFile={{ mongo_base_dir }}/certs/ca.pem&tlsCertificateKeyFile={{ mongo_base_dir }}/certs/secrets/mongodb.pem&directConnection=true" --eval '
    const currentConfig = rs.conf();
    let maxId = -1;
    for (const m of currentConfig.members) {
      if (m._id > maxId) maxId = m._id;
    }

    {% for host in groups["new_config_servers"] %}
    maxId++;
    rs.add({ _id: maxId, host: "{{ hostvars[host].ansible_host }}:{{ config_port }}" });
    sleep(1000);
    {% endfor %}
    '
  run_once: true
